### PR TITLE
add linearizedproductof to lowprioritycandidates for sample list form constraint

### PR DESCRIPTION
**Pull request by wouterwln**
See #340 for an explanation for this PR

### CODE REVIEW

**Comment by bvdmitri** [comment]
Perhaps this PR can also add `ProductOf` to the list?

**Comment by wouterwln** [comment]
`ProductOf` is covered by :
https://github.com/ReactiveBayes/RxInfer.jl/blob/318bd43a2e686e2150299a0295348a20cec8db21/src/constraints/form/form_sample_list.jl#L72-L76
We can add it to the list if you want, but I don't think it will ever be called.

**Comment by bvdmitri** [comment]
I also wonder why [this error message](https://github.com/ReactiveBayes/RxInfer.jl/pull/341/files#diff-f576c13db17a4312f4a2e6119af8f232039d3146d062a9511cdffbb9818b05b1R64) hasn't been showed in the #340 , perhaps the logic can be improved to guide users towards `LeftProposal/RightProposal`

**Comment by wouterwln** [comment]
But it will be covered since that function is recursive

**Review by bvdmitri — APPROVED** [review]
In any case, the PR is good, can be merged as is, my comments are more about further potential improvements

**Comment by bvdmitri** [comment]
> But it will be covered since that function is recursive

ah, you are right, my bad

**Pull request merged**
