### PR TITLE
fix Bayesian Linear Regression Tutorial

### PR DESCRIPTION
**Pull request by bvdmitri**
Part of the https://github.com/ReactiveBayes/RxInfer.jl/issues/242

### CODE REVIEW

**Comment by wouterwln** [comment]
Those posteriors look very suspicious to me. Are you sure you got the plotting straight?

**Comment by bvdmitri** [comment]
Aren't they the same as in the current demo https://reactivebayes.github.io/RxInfer.jl/stable/examples/basic_examples/Bayesian%20Linear%20Regression%20Tutorial/#examples-bayesian-linear-regression-tutorial ?

**Comment by bvdmitri** [comment]
I mean, they're certainly far from ideal, but it is what it is

**Comment by wouterwln** [comment]
You're right

**Pull request merged**
